class AppAsstes {
  static String onbord1 ="assets/images/Frame 3.png";
  static String onbord2 ="assets/images/Frame 13.png";
  static String onbord3 ="assets/images/Frame 3 (1).png";
  static String onbord4 ="assets/images/Frame 3 (2).png";
  static String onbord5 ="assets/images/Frame 3 (3).png";
  static String quran ="assets/images/ic_quran.png";
  static String hadith ="assets/images/book-album.png";
  static String sbha ="assets/images/necklace-islam-svgrepo-com 1.png";
  static String radio ="assets/images/radio-svgrepo-com 1.png";
  static String time ="assets/images/Vector.png";
  static String quranbg ="assets/images/Background.png";
  static String hadithbg ="assets/images/Background1.png";
  static String sbhabg ="assets/images/Background2.png";
  static String radiobg ="assets/images/Background3.png";
  static String timebg ="assets/images/Background4.png";
  static String mostRecently ="assets/images/img_most_recent.png";
  static String suraListNumberIcon ="assets/images/img_sur_number_frame.png";
  static String detailsPageBg ="assets/images/Group 38.png";
  static String hadithCarsBg ="assets/images/Group 39.png";
  static String sbhaImage ="assets/images/Group 40.png";
  static String radioPlay ="assets/images/Mask group.png";
  static String radioPlayed="assets/images/Mask group1.png";
  static String salahTimeBG="assets/images/Group 35.png";
  static String eveningAzkar="assets/images/bell-icon 1.png";
  static String morningAzkar="assets/images/comment-bubble-icon 1.png";
  static String wakingAzkar="assets/images/document-icon 1.png";
  static String sleepingAzkar="assets/images/document-icon 12.png";
}